version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .readthedoc configuration python version
      

sphinx:
  configuration: docs/conf.py
