language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - python --version
install:
  - pip install -U pip
  - pip install pipenv
  - PIPENV_IGNORE_VIRTUALENVS=1 pipenv install --dev
script:
  - PIPENV_IGNORE_VIRTUALENVS=1 pipenv run coverage run -m pytest
  - PIPENV_IGNORE_VIRTUALENVS=1 pipenv run coverage xml
after_success:
  - codecov -t 25fa2252-9440-46fa-b8dd-337e9de2a046
