language: python
python:
  - "3.7"
before_install:
  - python --version
install:
  - pip install -U pip
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run coverage run -m pytest
  - pipenv run coverage xml
after_success:
  - codecov -t 25fa2252-9440-46fa-b8dd-337e9de2a046
