language: python
python:
  - "3.7"
before_install:
  - python --version
install:
  - pip install -U pip
  - pip install pipenv pytest
  - pipenv install --dev
script:
  - pytest
after_success:
  - codecov
