language: python
python:
  - "3.7"
install:
  - pip install pipenv pytest
  - pipenv install --dev
script:
  - coverage run -m pytest
  - bash <(curl -s https://codecov.io/bash) -t 25fa2252-9440-46fa-b8dd-337e9de2a046
