language: python
git:
  depth: false
python:
  - "3.7"
env:
  - PIPENV_IGNORE_VIRTUALENVS=1
_shared_install: &shared_install
  install:
    - pip install -U pip
    - pip install pipenv
    - pipenv install --dev
jobs:
  include:
    - python: "3.7"
      <<: *shared_install
    - python:
        - "3.8"
        - "3.9"
      <<: *shared_install
        - pipenv install coverage
script:
  - pipenv run coverage run -m pytest
  - pipenv run coverage xml
after_success:
  - codecov -t 25fa2252-9440-46fa-b8dd-337e9de2a046
