// Do NOT edit this file as it is auto-generated by cws



provider "aws" {
  alias = "website-handless"
  profile = "fpr-customer"
  region = "eu-west-1"
}

# ---------------------------------------------------------------------------------------------------------------------
# LOCAL FOR THIS CUSTOMER
# ---------------------------------------------------------------------------------------------------------------------

locals {
  website-handless_when_default = terraform.workspace == "default" ? 1 : 0
  website-handless_when_stage = terraform.workspace != "default" ? 1 : 0
}

locals {
  website-handless_bucket = "coworks-microservice"
  website-handless_key = "website-handless/archive.zip"
  website-handless_python = "python3.7"
  website-handless_role_arn = join("", aws_iam_role.website-handless_microservice.*.arn, data.aws_iam_role.website-handless_microservice.*.arn)
  website-handless_security_group_ids = []
  website-handless_vpc_id = []
  website-handless_subnet_ids = []
  website-handless_tags = {
    Product: "microservice"
    Creator: "coworks"
  }
}


data "aws_lambda_layer_version" "website-handless" {
  provider = aws.website-handless
  for_each = {for layer_name in ["arn:aws:lambda:eu-west-1:935392763270:layer:coworks-dev"]: layer_name => layer_name}
  layer_name = each.value
}
locals {
  website-handless_layer_arns = [for layer in data.aws_lambda_layer_version.website-handless : layer.arn]
}



resource "aws_iam_role" "website-handless_microservice" {
  provider = aws.website-handless
  count = local.website-handless_when_default
  name = "website-handless_microservice_role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": [
          "lambda.amazonaws.com",
          "apigateway.amazonaws.com"
        ]
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF

  tags = {
    Product: "microservice"
    Creator: "coworks"
  }
}

resource "aws_iam_role_policy_attachment" "website-handless_s3" {
  provider = aws.website-handless
  count = local.website-handless_when_default
  role = join("", aws_iam_role.website-handless_microservice.*.name)
  policy_arn = "arn:aws:iam::aws:policy/AmazonS3FullAccess"
}

resource "aws_iam_role_policy_attachment" "website-handless_cloud_watch" {
  provider = aws.website-handless
  count = local.website-handless_when_default
  role = join("", aws_iam_role.website-handless_microservice.*.name)
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs"
}

resource "aws_iam_role_policy_attachment" "website-handless_xray" {
  provider = aws.website-handless
  count = local.website-handless_when_default
  role = join("", aws_iam_role.website-handless_microservice.*.name)
  policy_arn = "arn:aws:iam::aws:policy/AWSXrayFullAccess"
}

resource "aws_iam_role_policy_attachment" "website-handless_step_functions" {
  provider = aws.website-handless
  count = local.website-handless_when_default
  role = join("", aws_iam_role.website-handless_microservice.*.name)
  policy_arn = "arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess"
}

data "aws_iam_role" "website-handless_microservice" {
  provider = aws.website-handless
  count = local.website-handless_when_stage
  name = "website-handless_microservice_role"
}

locals {
  website-handless_api_id = join("", aws_api_gateway_rest_api.website-handless.*.id, data.aws_api_gateway_rest_api.website-handless.*.id)
  website-handless_api_root_id = join("", aws_api_gateway_rest_api.website-handless.*.root_resource_id, data.aws_api_gateway_rest_api.website-handless.*.root_resource_id)
  website-handless_lambda_uri = join("", aws_lambda_function.website-handless.*.invoke_arn, data.aws_lambda_function.website-handless.*.invoke_arn)
  website-handless_lambda_function_name = join("", aws_lambda_function.website-handless.*.function_name , data.aws_lambda_function.website-handless.*.function_name)
}


# ---------------------------------------------------------------------------------------------------------------------
# API GATEWAY
# ---------------------------------------------------------------------------------------------------------------------

resource "aws_api_gateway_rest_api" "website-handless" {
  provider = aws.website-handless
  count = local.website-handless_when_default
  name = "website-handless"
  description = ""
  
  tags = local.website-handless_tags

  lifecycle {
    prevent_destroy = true
  }
}

data "aws_api_gateway_rest_api" "website-handless" {
  provider = aws.website-handless
  count = local.website-handless_when_stage
  name = "website-handless"
}

resource "aws_api_gateway_authorizer" "website-handless" {
  provider = aws.website-handless
  count = local.website-handless_when_default
  name = "website-handless-auth"
  rest_api_id = local.website-handless_api_id
  authorizer_uri = local.website-handless_lambda_uri
}

# since at least one integration in needed to create api deployment we create an empty resource to prevent terraform from failing the first time we deploy the microservice
resource "aws_api_gateway_resource" "website-handless_null_resource" {
  provider = aws.website-handless
  count = 0
  path_part = "null_resource"
  parent_id = local.website-handless_api_root_id
  rest_api_id = local.website-handless_api_id
}
resource "aws_api_gateway_method" "website-handless_null_method" {
  provider = aws.website-handless
  count = 0
  rest_api_id = local.website-handless_api_id
  resource_id = join("", aws_api_gateway_resource.website-handless_null_resource.*.id)
  http_method = "GET"
  authorization = "NONE"
}
resource "aws_api_gateway_integration" "website-handless_null_integration" {
  provider = aws.website-handless
  count = 0
  rest_api_id = local.website-handless_api_id
  resource_id = join("", aws_api_gateway_resource.website-handless_null_resource.*.id)
  http_method = join("", aws_api_gateway_method.website-handless_null_method.*.http_method)
  integration_http_method = "GET"
  type = "MOCK"
}


    
      resource "aws_api_gateway_method" "website-handless___GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = local.website-handless_api_root_id
        http_method = "GET"
        
        authorization = "NONE"
        
      }

      resource "aws_api_gateway_integration" "website-handless___GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = local.website-handless_api_root_id
        http_method = join("", aws_api_gateway_method.website-handless___GET.*.http_method)
        integration_http_method = "POST"
        type = "AWS_PROXY"
        uri = local.website-handless_lambda_uri
      }
    

    
      resource "aws_api_gateway_method" "website-handless___OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = local.website-handless_api_root_id
        http_method = "OPTIONS"
        authorization = "NONE"
      }

      resource "aws_api_gateway_integration" "website-handless___OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = local.website-handless_api_root_id
        http_method = join("", aws_api_gateway_method.website-handless___OPTIONS.*.http_method)
        type = "MOCK"
        request_templates = {
          "application/json" = "{ \"statusCode\": 200 }"
        }
      }

      resource "aws_api_gateway_integration_response" "website-handless___OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = local.website-handless_api_root_id
        http_method =  join("", aws_api_gateway_method.website-handless___OPTIONS.*.http_method)
        response_parameters = {
          "method.response.header.Access-Control-Allow-Origin" = "'*'",
          "method.response.header.Access-Control-Allow-Headers" = "'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key'",
          "method.response.header.Access-Control-Max-Age" = "'600'",
        }
        status_code = 200
        response_templates = {
          "application/json": "{}"
        }
        depends_on = [
          aws_api_gateway_integration.website-handless___OPTIONS,
          aws_api_gateway_method_response.website-handless___OPTIONS,
        ]
      }

      resource "aws_api_gateway_method_response" "website-handless___OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = local.website-handless_api_root_id
        http_method = join("", aws_api_gateway_method.website-handless___OPTIONS.*.http_method)
        status_code = 200
        response_models = {
          "application/json" = "Empty"
        }
        response_parameters = {
          "method.response.header.Access-Control-Allow-Headers" = true,
          "method.response.header.Access-Control-Allow-Methods" = true,
          "method.response.header.Access-Control-Allow-Origin" = true,
          "method.response.header.Access-Control-Max-Age" = true,
        }

        depends_on = [
          aws_api_gateway_method.website-handless___OPTIONS,
        ]
      }
    
    resource "aws_api_gateway_resource" "website-handless___assets" {
      provider = aws.website-handless
      count = local.website-handless_when_default
      rest_api_id = local.website-handless_api_id
      
      parent_id = local.website-handless_api_root_id
      
      path_part = "assets"
    }
  
    resource "aws_api_gateway_resource" "website-handless___assets__0" {
      provider = aws.website-handless
      count = local.website-handless_when_default
      rest_api_id = local.website-handless_api_id
      
      parent_id = aws_api_gateway_resource.website-handless___assets[0].id
      
      path_part = "{_0}"
    }
  
    resource "aws_api_gateway_resource" "website-handless___assets__0__1" {
      provider = aws.website-handless
      count = local.website-handless_when_default
      rest_api_id = local.website-handless_api_id
      
      parent_id = aws_api_gateway_resource.website-handless___assets__0[0].id
      
      path_part = "{_1}"
    }
  
    
      resource "aws_api_gateway_method" "website-handless___assets__0__1_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1[0].id
        http_method = "GET"
        
        authorization = "NONE"
        
      }

      resource "aws_api_gateway_integration" "website-handless___assets__0__1_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1[0].id
        http_method = join("", aws_api_gateway_method.website-handless___assets__0__1_GET.*.http_method)
        integration_http_method = "POST"
        type = "AWS_PROXY"
        uri = local.website-handless_lambda_uri
      }
    

    
      resource "aws_api_gateway_method" "website-handless___assets__0__1_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1[0].id
        http_method = "OPTIONS"
        authorization = "NONE"
      }

      resource "aws_api_gateway_integration" "website-handless___assets__0__1_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1[0].id
        http_method = join("", aws_api_gateway_method.website-handless___assets__0__1_OPTIONS.*.http_method)
        type = "MOCK"
        request_templates = {
          "application/json" = "{ \"statusCode\": 200 }"
        }
      }

      resource "aws_api_gateway_integration_response" "website-handless___assets__0__1_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1[0].id
        http_method =  join("", aws_api_gateway_method.website-handless___assets__0__1_OPTIONS.*.http_method)
        response_parameters = {
          "method.response.header.Access-Control-Allow-Origin" = "'*'",
          "method.response.header.Access-Control-Allow-Headers" = "'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key'",
          "method.response.header.Access-Control-Max-Age" = "'600'",
        }
        status_code = 200
        response_templates = {
          "application/json": "{}"
        }
        depends_on = [
          aws_api_gateway_integration.website-handless___assets__0__1_OPTIONS,
          aws_api_gateway_method_response.website-handless___assets__0__1_OPTIONS,
        ]
      }

      resource "aws_api_gateway_method_response" "website-handless___assets__0__1_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1[0].id
        http_method = join("", aws_api_gateway_method.website-handless___assets__0__1_OPTIONS.*.http_method)
        status_code = 200
        response_models = {
          "application/json" = "Empty"
        }
        response_parameters = {
          "method.response.header.Access-Control-Allow-Headers" = true,
          "method.response.header.Access-Control-Allow-Methods" = true,
          "method.response.header.Access-Control-Allow-Origin" = true,
          "method.response.header.Access-Control-Max-Age" = true,
        }

        depends_on = [
          aws_api_gateway_method.website-handless___assets__0__1_OPTIONS,
        ]
      }
    
    resource "aws_api_gateway_resource" "website-handless___assets__0__1__2" {
      provider = aws.website-handless
      count = local.website-handless_when_default
      rest_api_id = local.website-handless_api_id
      
      parent_id = aws_api_gateway_resource.website-handless___assets__0__1[0].id
      
      path_part = "{_2}"
    }
  
    
      resource "aws_api_gateway_method" "website-handless___assets__0__1__2_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1__2[0].id
        http_method = "GET"
        
        authorization = "NONE"
        
      }

      resource "aws_api_gateway_integration" "website-handless___assets__0__1__2_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1__2[0].id
        http_method = join("", aws_api_gateway_method.website-handless___assets__0__1__2_GET.*.http_method)
        integration_http_method = "POST"
        type = "AWS_PROXY"
        uri = local.website-handless_lambda_uri
      }
    

    
      resource "aws_api_gateway_method" "website-handless___assets__0__1__2_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1__2[0].id
        http_method = "OPTIONS"
        authorization = "NONE"
      }

      resource "aws_api_gateway_integration" "website-handless___assets__0__1__2_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1__2[0].id
        http_method = join("", aws_api_gateway_method.website-handless___assets__0__1__2_OPTIONS.*.http_method)
        type = "MOCK"
        request_templates = {
          "application/json" = "{ \"statusCode\": 200 }"
        }
      }

      resource "aws_api_gateway_integration_response" "website-handless___assets__0__1__2_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1__2[0].id
        http_method =  join("", aws_api_gateway_method.website-handless___assets__0__1__2_OPTIONS.*.http_method)
        response_parameters = {
          "method.response.header.Access-Control-Allow-Origin" = "'*'",
          "method.response.header.Access-Control-Allow-Headers" = "'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key'",
          "method.response.header.Access-Control-Max-Age" = "'600'",
        }
        status_code = 200
        response_templates = {
          "application/json": "{}"
        }
        depends_on = [
          aws_api_gateway_integration.website-handless___assets__0__1__2_OPTIONS,
          aws_api_gateway_method_response.website-handless___assets__0__1__2_OPTIONS,
        ]
      }

      resource "aws_api_gateway_method_response" "website-handless___assets__0__1__2_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___assets__0__1__2[0].id
        http_method = join("", aws_api_gateway_method.website-handless___assets__0__1__2_OPTIONS.*.http_method)
        status_code = 200
        response_models = {
          "application/json" = "Empty"
        }
        response_parameters = {
          "method.response.header.Access-Control-Allow-Headers" = true,
          "method.response.header.Access-Control-Allow-Methods" = true,
          "method.response.header.Access-Control-Allow-Origin" = true,
          "method.response.header.Access-Control-Max-Age" = true,
        }

        depends_on = [
          aws_api_gateway_method.website-handless___assets__0__1__2_OPTIONS,
        ]
      }
    
    resource "aws_api_gateway_resource" "website-handless___form" {
      provider = aws.website-handless
      count = local.website-handless_when_default
      rest_api_id = local.website-handless_api_id
      
      parent_id = local.website-handless_api_root_id
      
      path_part = "form"
    }
  
    
      resource "aws_api_gateway_method" "website-handless___form_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___form[0].id
        http_method = "GET"
        
        authorization = "NONE"
        
      }

      resource "aws_api_gateway_integration" "website-handless___form_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___form[0].id
        http_method = join("", aws_api_gateway_method.website-handless___form_GET.*.http_method)
        integration_http_method = "POST"
        type = "AWS_PROXY"
        uri = local.website-handless_lambda_uri
      }
    

    
      resource "aws_api_gateway_method" "website-handless___form_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___form[0].id
        http_method = "OPTIONS"
        authorization = "NONE"
      }

      resource "aws_api_gateway_integration" "website-handless___form_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___form[0].id
        http_method = join("", aws_api_gateway_method.website-handless___form_OPTIONS.*.http_method)
        type = "MOCK"
        request_templates = {
          "application/json" = "{ \"statusCode\": 200 }"
        }
      }

      resource "aws_api_gateway_integration_response" "website-handless___form_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___form[0].id
        http_method =  join("", aws_api_gateway_method.website-handless___form_OPTIONS.*.http_method)
        response_parameters = {
          "method.response.header.Access-Control-Allow-Origin" = "'*'",
          "method.response.header.Access-Control-Allow-Headers" = "'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key'",
          "method.response.header.Access-Control-Max-Age" = "'600'",
        }
        status_code = 200
        response_templates = {
          "application/json": "{}"
        }
        depends_on = [
          aws_api_gateway_integration.website-handless___form_OPTIONS,
          aws_api_gateway_method_response.website-handless___form_OPTIONS,
        ]
      }

      resource "aws_api_gateway_method_response" "website-handless___form_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___form[0].id
        http_method = join("", aws_api_gateway_method.website-handless___form_OPTIONS.*.http_method)
        status_code = 200
        response_models = {
          "application/json" = "Empty"
        }
        response_parameters = {
          "method.response.header.Access-Control-Allow-Headers" = true,
          "method.response.header.Access-Control-Allow-Methods" = true,
          "method.response.header.Access-Control-Allow-Origin" = true,
          "method.response.header.Access-Control-Max-Age" = true,
        }

        depends_on = [
          aws_api_gateway_method.website-handless___form_OPTIONS,
        ]
      }
    
    resource "aws_api_gateway_resource" "website-handless___product" {
      provider = aws.website-handless
      count = local.website-handless_when_default
      rest_api_id = local.website-handless_api_id
      
      parent_id = local.website-handless_api_root_id
      
      path_part = "product"
    }
  
    resource "aws_api_gateway_resource" "website-handless___product__0" {
      provider = aws.website-handless
      count = local.website-handless_when_default
      rest_api_id = local.website-handless_api_id
      
      parent_id = aws_api_gateway_resource.website-handless___product[0].id
      
      path_part = "{_0}"
    }
  
    
      resource "aws_api_gateway_method" "website-handless___product__0_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___product__0[0].id
        http_method = "GET"
        
        authorization = "NONE"
        
      }

      resource "aws_api_gateway_integration" "website-handless___product__0_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___product__0[0].id
        http_method = join("", aws_api_gateway_method.website-handless___product__0_GET.*.http_method)
        integration_http_method = "POST"
        type = "AWS_PROXY"
        uri = local.website-handless_lambda_uri
      }
    

    
      resource "aws_api_gateway_method" "website-handless___product__0_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___product__0[0].id
        http_method = "OPTIONS"
        authorization = "NONE"
      }

      resource "aws_api_gateway_integration" "website-handless___product__0_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___product__0[0].id
        http_method = join("", aws_api_gateway_method.website-handless___product__0_OPTIONS.*.http_method)
        type = "MOCK"
        request_templates = {
          "application/json" = "{ \"statusCode\": 200 }"
        }
      }

      resource "aws_api_gateway_integration_response" "website-handless___product__0_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___product__0[0].id
        http_method =  join("", aws_api_gateway_method.website-handless___product__0_OPTIONS.*.http_method)
        response_parameters = {
          "method.response.header.Access-Control-Allow-Origin" = "'*'",
          "method.response.header.Access-Control-Allow-Headers" = "'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key'",
          "method.response.header.Access-Control-Max-Age" = "'600'",
        }
        status_code = 200
        response_templates = {
          "application/json": "{}"
        }
        depends_on = [
          aws_api_gateway_integration.website-handless___product__0_OPTIONS,
          aws_api_gateway_method_response.website-handless___product__0_OPTIONS,
        ]
      }

      resource "aws_api_gateway_method_response" "website-handless___product__0_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___product__0[0].id
        http_method = join("", aws_api_gateway_method.website-handless___product__0_OPTIONS.*.http_method)
        status_code = 200
        response_models = {
          "application/json" = "Empty"
        }
        response_parameters = {
          "method.response.header.Access-Control-Allow-Headers" = true,
          "method.response.header.Access-Control-Allow-Methods" = true,
          "method.response.header.Access-Control-Allow-Origin" = true,
          "method.response.header.Access-Control-Max-Age" = true,
        }

        depends_on = [
          aws_api_gateway_method.website-handless___product__0_OPTIONS,
        ]
      }
    
    resource "aws_api_gateway_resource" "website-handless___admin" {
      provider = aws.website-handless
      count = local.website-handless_when_default
      rest_api_id = local.website-handless_api_id
      
      parent_id = local.website-handless_api_root_id
      
      path_part = "admin"
    }
  
    resource "aws_api_gateway_resource" "website-handless___admin_context" {
      provider = aws.website-handless
      count = local.website-handless_when_default
      rest_api_id = local.website-handless_api_id
      
      parent_id = aws_api_gateway_resource.website-handless___admin[0].id
      
      path_part = "context"
    }
  
    
      resource "aws_api_gateway_method" "website-handless___admin_context_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_context[0].id
        http_method = "GET"
        
        authorization = "NONE"
        
      }

      resource "aws_api_gateway_integration" "website-handless___admin_context_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_context[0].id
        http_method = join("", aws_api_gateway_method.website-handless___admin_context_GET.*.http_method)
        integration_http_method = "POST"
        type = "AWS_PROXY"
        uri = local.website-handless_lambda_uri
      }
    

    
      resource "aws_api_gateway_method" "website-handless___admin_context_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_context[0].id
        http_method = "OPTIONS"
        authorization = "NONE"
      }

      resource "aws_api_gateway_integration" "website-handless___admin_context_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_context[0].id
        http_method = join("", aws_api_gateway_method.website-handless___admin_context_OPTIONS.*.http_method)
        type = "MOCK"
        request_templates = {
          "application/json" = "{ \"statusCode\": 200 }"
        }
      }

      resource "aws_api_gateway_integration_response" "website-handless___admin_context_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_context[0].id
        http_method =  join("", aws_api_gateway_method.website-handless___admin_context_OPTIONS.*.http_method)
        response_parameters = {
          "method.response.header.Access-Control-Allow-Origin" = "'*'",
          "method.response.header.Access-Control-Allow-Headers" = "'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key'",
          "method.response.header.Access-Control-Max-Age" = "'600'",
        }
        status_code = 200
        response_templates = {
          "application/json": "{}"
        }
        depends_on = [
          aws_api_gateway_integration.website-handless___admin_context_OPTIONS,
          aws_api_gateway_method_response.website-handless___admin_context_OPTIONS,
        ]
      }

      resource "aws_api_gateway_method_response" "website-handless___admin_context_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_context[0].id
        http_method = join("", aws_api_gateway_method.website-handless___admin_context_OPTIONS.*.http_method)
        status_code = 200
        response_models = {
          "application/json" = "Empty"
        }
        response_parameters = {
          "method.response.header.Access-Control-Allow-Headers" = true,
          "method.response.header.Access-Control-Allow-Methods" = true,
          "method.response.header.Access-Control-Allow-Origin" = true,
          "method.response.header.Access-Control-Max-Age" = true,
        }

        depends_on = [
          aws_api_gateway_method.website-handless___admin_context_OPTIONS,
        ]
      }
    
    resource "aws_api_gateway_resource" "website-handless___admin_proxy" {
      provider = aws.website-handless
      count = local.website-handless_when_default
      rest_api_id = local.website-handless_api_id
      
      parent_id = aws_api_gateway_resource.website-handless___admin[0].id
      
      path_part = "proxy"
    }
  
    
      resource "aws_api_gateway_method" "website-handless___admin_proxy_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_proxy[0].id
        http_method = "GET"
        
        authorization = "NONE"
        
      }

      resource "aws_api_gateway_integration" "website-handless___admin_proxy_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_proxy[0].id
        http_method = join("", aws_api_gateway_method.website-handless___admin_proxy_GET.*.http_method)
        integration_http_method = "POST"
        type = "AWS_PROXY"
        uri = local.website-handless_lambda_uri
      }
    

    
      resource "aws_api_gateway_method" "website-handless___admin_proxy_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_proxy[0].id
        http_method = "OPTIONS"
        authorization = "NONE"
      }

      resource "aws_api_gateway_integration" "website-handless___admin_proxy_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_proxy[0].id
        http_method = join("", aws_api_gateway_method.website-handless___admin_proxy_OPTIONS.*.http_method)
        type = "MOCK"
        request_templates = {
          "application/json" = "{ \"statusCode\": 200 }"
        }
      }

      resource "aws_api_gateway_integration_response" "website-handless___admin_proxy_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_proxy[0].id
        http_method =  join("", aws_api_gateway_method.website-handless___admin_proxy_OPTIONS.*.http_method)
        response_parameters = {
          "method.response.header.Access-Control-Allow-Origin" = "'*'",
          "method.response.header.Access-Control-Allow-Headers" = "'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key'",
          "method.response.header.Access-Control-Max-Age" = "'600'",
        }
        status_code = 200
        response_templates = {
          "application/json": "{}"
        }
        depends_on = [
          aws_api_gateway_integration.website-handless___admin_proxy_OPTIONS,
          aws_api_gateway_method_response.website-handless___admin_proxy_OPTIONS,
        ]
      }

      resource "aws_api_gateway_method_response" "website-handless___admin_proxy_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_proxy[0].id
        http_method = join("", aws_api_gateway_method.website-handless___admin_proxy_OPTIONS.*.http_method)
        status_code = 200
        response_models = {
          "application/json" = "Empty"
        }
        response_parameters = {
          "method.response.header.Access-Control-Allow-Headers" = true,
          "method.response.header.Access-Control-Allow-Methods" = true,
          "method.response.header.Access-Control-Allow-Origin" = true,
          "method.response.header.Access-Control-Max-Age" = true,
        }

        depends_on = [
          aws_api_gateway_method.website-handless___admin_proxy_OPTIONS,
        ]
      }
    
    resource "aws_api_gateway_resource" "website-handless___admin_routes" {
      provider = aws.website-handless
      count = local.website-handless_when_default
      rest_api_id = local.website-handless_api_id
      
      parent_id = aws_api_gateway_resource.website-handless___admin[0].id
      
      path_part = "routes"
    }
  
    
      resource "aws_api_gateway_method" "website-handless___admin_routes_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_routes[0].id
        http_method = "GET"
        
        authorization = "NONE"
        
      }

      resource "aws_api_gateway_integration" "website-handless___admin_routes_GET" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_routes[0].id
        http_method = join("", aws_api_gateway_method.website-handless___admin_routes_GET.*.http_method)
        integration_http_method = "POST"
        type = "AWS_PROXY"
        uri = local.website-handless_lambda_uri
      }
    

    
      resource "aws_api_gateway_method" "website-handless___admin_routes_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_routes[0].id
        http_method = "OPTIONS"
        authorization = "NONE"
      }

      resource "aws_api_gateway_integration" "website-handless___admin_routes_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_routes[0].id
        http_method = join("", aws_api_gateway_method.website-handless___admin_routes_OPTIONS.*.http_method)
        type = "MOCK"
        request_templates = {
          "application/json" = "{ \"statusCode\": 200 }"
        }
      }

      resource "aws_api_gateway_integration_response" "website-handless___admin_routes_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_routes[0].id
        http_method =  join("", aws_api_gateway_method.website-handless___admin_routes_OPTIONS.*.http_method)
        response_parameters = {
          "method.response.header.Access-Control-Allow-Origin" = "'*'",
          "method.response.header.Access-Control-Allow-Headers" = "'Authorization,Content-Type,X-Amz-Date,X-Amz-Security-Token,X-Api-Key'",
          "method.response.header.Access-Control-Max-Age" = "'600'",
        }
        status_code = 200
        response_templates = {
          "application/json": "{}"
        }
        depends_on = [
          aws_api_gateway_integration.website-handless___admin_routes_OPTIONS,
          aws_api_gateway_method_response.website-handless___admin_routes_OPTIONS,
        ]
      }

      resource "aws_api_gateway_method_response" "website-handless___admin_routes_OPTIONS" {
        provider = aws.website-handless
        count = local.website-handless_when_default
        rest_api_id = local.website-handless_api_id
        resource_id = aws_api_gateway_resource.website-handless___admin_routes[0].id
        http_method = join("", aws_api_gateway_method.website-handless___admin_routes_OPTIONS.*.http_method)
        status_code = 200
        response_models = {
          "application/json" = "Empty"
        }
        response_parameters = {
          "method.response.header.Access-Control-Allow-Headers" = true,
          "method.response.header.Access-Control-Allow-Methods" = true,
          "method.response.header.Access-Control-Allow-Origin" = true,
          "method.response.header.Access-Control-Max-Age" = true,
        }

        depends_on = [
          aws_api_gateway_method.website-handless___admin_routes_OPTIONS,
        ]
      }
    



resource "aws_api_gateway_deployment" "website-handless" {
  provider = aws.website-handless
  count = local.website-handless_when_stage
  rest_api_id = local.website-handless_api_id

  
  triggers = {
    timestamp = timestamp() 
  }
  lifecycle {
    create_before_destroy = true
  }
  
}

resource "aws_api_gateway_stage" "website-handless" {
  provider = aws.website-handless
  count = local.website-handless_when_stage
  stage_name = terraform.workspace
  rest_api_id = local.website-handless_api_id
  deployment_id = aws_api_gateway_deployment.website-handless[0].id
  xray_tracing_enabled = true
}

# ---------------------------------------------------------------------------------------------------------------------
# OUTPUT
# ---------------------------------------------------------------------------------------------------------------------

output "website-handless" {
value = {
    "id" = terraform.workspace == "default" ? aws_api_gateway_rest_api.website-handless[0].id : ""
  }
}

locals {
    
    website-handless_environment_variables = [
        for envars_string in data.local_file.website-handless_environment_variables_files: jsondecode(envars_string.content)
    ]
    
}

# ---------------------------------------------------------------------------------------------------------------------
# LAMBDA
# ---------------------------------------------------------------------------------------------------------------------

data "aws_s3_bucket_object" "website-handless-b64sha256" {
  provider = aws.website-handless
  bucket = local.website-handless_bucket
  key = "${local.website-handless_key}.b64sha256"
}


data "local_file" "website-handless_environment_variables_files" {
  for_each = {for envar_file in ["vars.secret.json"]: envar_file => "../${envar_file}"}
  filename = each.value
}


resource "aws_lambda_function" "website-handless" {
  provider = aws.website-handless
  count = local.website-handless_when_stage
  function_name = "website-handless-${terraform.workspace}"
  s3_bucket = local.website-handless_bucket
  s3_key = local.website-handless_key
  source_code_hash =  data.aws_s3_bucket_object.website-handless-b64sha256.body
  role = local.website-handless_role_arn
  handler = "website.app"
  
  layers = local.website-handless_layer_arns
  
  runtime = local.website-handless_python
  timeout = 30
  memory_size = 128
  
  environment {
    variables = merge({"ASSETS_URL": "https://draft.morassuti.com"},[for item in local.website-handless_environment_variables: merge(item,local.website-handless_environment_variables...)][0], {"WORKSPACE":"dev"})
  }
  
  tracing_config {
    mode = "Active"
  }
  vpc_config {
    security_group_ids = local.website-handless_security_group_ids
    subnet_ids = local.website-handless_subnet_ids
  }
  tags = local.website-handless_tags
}

data "aws_lambda_function" "website-handless" {
  provider = aws.website-handless
  count = local.website-handless_when_default
  function_name = "website-handless-dev"
}

resource "aws_lambda_permission" "website-handless" {
  provider = aws.website-handless
  count = local.website-handless_when_stage
  statement_id = "AllowExecutionFromAPIGateway"
  action = "lambda:InvokeFunction"
  function_name = local.website-handless_lambda_function_name
  principal = "apigateway.amazonaws.com"
  source_arn = "${join("", data.aws_api_gateway_rest_api.website-handless.*.execution_arn)}/*/*"
  depends_on = [aws_lambda_function.website-handless]
}
