###

GET http://localhost:8000/describe

###

GET http://localhost:8000/last/1

###

GET http://localhost:8000/execution/arn:aws:states:eu-west-1:848422798754:execution:HelloWorld:320efd62-a00f-48ba-990d-0f85e01e50c8

###

POST http://localhost:8000/invoke
Content-Type: application/json

{
  "name":""
}

###
