info:
  description: {{ app.__doc__ }}
  title: {{ name }}
openapi: 3.0.0
paths:
{% for entry, (method, func) in app.entries.items() %}
  {{ entry }}:
    {{ method }}:
      description: {{ func.__doc__ }}
  {% endfor %}
version: {{ app.version }}
