name: Upload CoWorks Python Package

on: push

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install -G dev

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Run tests
        run: pdm run on_github

      - name: Publish package distributions to PyPI
        if: github.ref_name == 'master'
        run: pdm publish
